[package]
name = "rust-executor"
version = "0.8.0-prerelease"
edition = "2021"
authors = ["Nicolas Luck <nicolas@perspect3vism.org>"]
description = "A command-line interface to AD4M (i.e. the AD4M executor) - https://ad4m.dev"
keywords = ["ad4m", "perspect3vism", "cli"]
license = "CAL-1.0"
homepage = "https://ad4m.dev"
repository = "https://github.com/perspect3vism/ad4m"
documentation = "https://docs.ad4m.dev"
readme = "README.md"

[lib]
name = "rust_executor"
path = "src/lib.rs"

[[bin]]
name = "rust_executor_bin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.218.0"
deno_runtime = "0.128.0"
tokio = { version = "1.25.0", features = ["full"] }
url = "2.3.1"
futures = "0.3.28"
tokio-stream = { version = "0.1.12", features = ["sync"] }
lazy_static = "1.4.0"

chrono = { version = "0.4.30", features = ["serde"] }
env_logger = "0.10.0"
serde_json = "1.0.95"
uuid = "1.3.0"
log = "0.4.19"
serde = "1.0.159"
secp256k1 = { version = "0.27.0", features = ["rand", "serde"] }
crypto_box = "0.8.2"
hex = "0.4.3"
argon2 = { version = "0.5.0", features = ["simple"] }
rand = "0.8.5"
base64 = "0.21.0"
clap = { version = "4.0.8", features = ["derive"] }
fs_extra = "1.3.0"
os_info = "3.7.0"
semver = "1.0.17"
did-key = "0.2.1"
zip = "0.6.4"
multibase = "0.9.1"
multihash = { version = "0.18.0", features = ["sha2"] }
cid = "0.10.1"
once_cell = "1.17.1"
hyper = { version = "1.0.0-rc.4", features = ["full"] }
http-body-util = "0.1.0-rc.3"
hyper-util = { git = "https://github.com/hyperium/hyper-util.git" }
rust-embed="8.0.0"
dirs = "5.0.1"

juniper = { git = "https://github.com/graphql-rust/juniper", features = ["chrono"], rev = "57628de8649be071b04a3fedb45c47add7dc5192" }
juniper_subscriptions = { git = "https://github.com/graphql-rust/juniper", rev = "57628de8649be071b04a3fedb45c47add7dc5192" }
juniper_graphql_transport_ws = { git = "https://github.com/graphql-rust/juniper", rev = "57628de8649be071b04a3fedb45c47add7dc5192" }
juniper_warp = { git = "https://github.com/graphql-rust/juniper", features = ["subscriptions"], rev = "57628de8649be071b04a3fedb45c47add7dc5192" }
warp = "0.3.4"

jsonwebtoken = "8.3.0"

holochain = { version = "0.2.2", features = ["test_utils", "default"] }
holochain_cli_bundle = { version = "0.2.2" }
holochain_types = { version = "0.2.2" }
holochain_cli_run_local_services = { version = "0.2.2" }

scryer-prolog = { version = "0.9.1", git = "https://github.com/coasys/scryer-prolog", rev = "941a349165539aed1637e54cdc40417096424021", features = ["multi_thread"] }
# scryer-prolog = { path = "../../scryer-prolog", features = ["multi_thread"] }

[dev-dependencies]
maplit = "1.0.2"
