[package]
name = "rust-executor"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_executor"
path = "src/lib.rs"

[[bin]]
name = "rust_executor_bin"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.179.0"
deno_runtime = "0.105.0"
tokio = { version = "1.25.0", features = ["full"] }
url = "2.3.1"
futures = "0.3.28"
tokio-stream = { version = "0.1.12", features = ["sync"] }
lazy_static = "1.4.0"

chrono = { version = "0.4.24", features = ["serde"] }
env_logger = "0.10.0"
serde_json = "1.0.95"
uuid = "1.3.0"
log = "0.4.17"
serde = "1.0.159"
secp256k1 = { version = "0.27.0", features = ["rand", "serde"] }
crypto_box = "0.8.2"
hex = "0.4.3"
argon2 = { version = "0.5.0", features = ["simple"] }
rand = "0.8.5"
base64 = "0.21.0"
clap = { version = "4.0.8", features = ["derive"] }
fs_extra = "1.3.0"
os_info = "3.7.0"
semver = "1.0.17"
did-key = "0.2.1"
zip = "0.6.4"
multibase = "0.9.1"
multihash = { version = "0.18.0", features = ["sha2"] }
cid = "0.10.1"
once_cell = "1.17.1"

juniper = { git = "https://github.com/graphql-rust/juniper", branch = "graphql-transport-ws-protocol", features = ["chrono"] }
juniper_subscriptions = {git = "https://github.com/graphql-rust/juniper", branch = "graphql-transport-ws-protocol" }
juniper_graphql_transport_ws = { git = "https://github.com/graphql-rust/juniper", branch = "graphql-transport-ws-protocol" }
juniper_warp = { git = "https://github.com/graphql-rust/juniper", branch = "graphql-transport-ws-protocol", features = ["subscriptions"] }
warp = "0.3.4"

jsonwebtoken = "8.3.0"

holochain = "0.1.3"

scryer-prolog = "0.9.1"
