[package]
name = "ad4m-client"
version = "0.5.0"
edition = "2021"
authors = ["Nicolas Luck <nicolas@perspect3vism.org>"]
description = "Client library wrapping AD4M's GraphQL interface"
keywords = ["ad4m", "perspect3vism", "cli"]
license = "CAL-1.0"
homepage = "https://ad4m.dev"
repository = "https://github.com/perspect3vism/ad4m"
documentation = "https://docs.ad4m.dev"
readme = "README.md"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.8", features = ["derive"] }
graphql_client = "0.10.0"
serde = "1.0.147"
reqwest = { version = "0.11.12", features = ["blocking", "json"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
rustyline = "10"
dirs = "4"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1"
graphql-ws-client = { version = "0.2", default-features = false, features = ["async-tungstenite", "cynic", "graphql_client"] }
async-tungstenite = { version = "0.16.1", features = ["async-std-runtime", "tokio-runtime"] }
cynic = { version = "1.0" }
async-std = { version = "1.9", features = ["attributes"] }
async_executors = { version = "0.5", features = ["async_std"] }
urlencoding = "2"
unicode-width = "0.1"
rand = "0.8"
regex = "1"
maplit = "1"
