packages:
  # all packages in direct subdirs of packages/
  - 'core'
  - 'docs'
  - 'executor'
  - 'ui'
  - 'connect'
  - 'bootstrap-languages/*'
  - 'tests/js'
  - 'rust-executor'
  - 'cli'
  - 'dapp'
  - 'ad4m-hooks/react'
  - 'ad4m-hooks/vue'
  - 'ad4m-hooks/helpers'
  # exclude packages that are inside test directories
  - '!**/test/**'
hoist: false
public-hoist-pattern: '!core'
overrides:
  core:
    hoist: false