version: 2.1

orbs:
  node: circleci/node@5.2.0
  go: circleci/go@1.10.0
  rust: circleci/rust@1.6.1

jobs:
  test-linux:
    parameters:
      node-version:
        type: string
        default: "16.20.2"
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - rust/install:
          version: "1.73.0"
      - go/install:
          version: "1.20"
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf protobuf-compiler cmake
      - restore_cache:
          keys:
            - hc-0.3.0-beta-dev.27
            - hc-
      - run:
          name: Install HC
          command: |
            if [ ! -f "$HOME/.cargo/bin/hc" ]; then
              cargo install holochain_cli --version 0.3.0-beta-dev.27
            fi
      - save_cache:
          key: hc-0.3.0-beta-dev.27
          paths:
            - "$HOME/.cargo/bin/hc"
      - run:
          name: Install pnpm
          command: npm install -g pnpm
      - run:
          name: Install dependencies
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Build the workspace
          command: pnpm run build
      - run:
          name: Run the tests
          command: pnpm test
      - run:
          name: Run integration tests
          command: cd ./tests/js && pnpm run test-main

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-linux:
          matrix:
            parameters:
              node-version: ["16.20.2"]
