version: 2.1

orbs:
  node: circleci/node@5.2.0
  go: circleci/go@1.10.0
  rust: circleci/rust@1.6.1

jobs:
  build:
    docker:
      - image: coasys/ad4m-ci-linux:latest@sha256:7008f587d355d1adeb58553f52f99e1812822b4d21dc78d69bc96040d5e57e82
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - hc-0.3.0-beta-dev-27-v7
            - hc-
            - rust-cache-{{ checksum "Cargo.lock" }}
            - rust-cache-
      - run:
          name: Install HC
          command: |
            ls -la $HOME/.cargo/bin
            if [ ! -f "$HOME/.cargo/bin/hc" ]; then
              git clone https://github.com/holochain/holochain.git
              cd holochain
              git checkout holochain-0.3.0-beta-dev.27
              cd crates/hc
              cargo build --release
              pwd
              ls -la 
              mkdir -p $HOME/.cargo/bin
              cd ../../target/release
              pwd
              ls -lah
              cp hc $HOME/.cargo/bin/hc
              cd $HOME/.cargo/bin
              pwd
              ls -lah
              ./hc --version
            fi
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - save_cache:
          key: hc-0.3.0-beta-dev-27-v7
          paths:
            - /home/circleci/.cargo/bin
      - restore_cache:
          keys:
            - rust-cache-{{ checksum "Cargo.lock" }}-v2
            - rust-cache-
      - run:
          name: Install dependencies
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Build ADAM (without bootstrap languages)
          command: pnpm run build-libs
      - save_cache:
          key: rust-cache-{{ checksum "Cargo.lock" }}-v2
          paths:
            - ./target
            - ~/.cargo/registry
            - ~/.cargo/git
      - persist_to_workspace:
          no-output-timeout: 30m
          root: .
          paths:
            - .

  unit-tests:
    docker:
      - image: coasys/ad4m-ci-linux:latest@sha256:7008f587d355d1adeb58553f52f99e1812822b4d21dc78d69bc96040d5e57e82
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Root tests
          command: pnpm test

  integration-tests-js:
    docker:
      - image: coasys/ad4m-ci-linux:latest@sha256:7008f587d355d1adeb58553f52f99e1812822b4d21dc78d69bc96040d5e57e82
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - hc-0.3.0-beta-dev-27-v7
            - hc-
      - restore_cache:
          keys:
            - rust-cache-{{ checksum "Cargo.lock" }}-v2
            - rust-cache-
      - run:
          name: Install dependencies
          command: pnpm install --no-frozen-lockfile
      - run:
          name: Build bootstrap languages
          command: pnpm run build-languages
      - run:
          name: Run integration tests
          command: cd ./tests/js && pnpm run test-main

  integration-tests-cli:
    docker:
      - image: coasys/ad4m-ci-linux:latest@sha256:7008f587d355d1adeb58553f52f99e1812822b4d21dc78d69bc96040d5e57e82
    steps:
      - attach_workspace:
          at: .
      - run:
          name: git submodule
          command: git submodule update --init --recursive
      - run:
          name: Run binaries test script
          command: ./tests/bats/bin/bats tests/binaries.bats
      - run:
          name: Run integration test script
          command: ./tests/bats/bin/bats tests/integration.bats

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - integration-tests-js:
          requires:
            - build
      - integration-tests-cli:
          requires:
            - build
