name: Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    name: AD4M cli
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2

    - name: git init submodule
      run: git submodule init && git submodule update

    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        override: true
        toolchain: 1.68.2

    - name: Cache cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - run: rustup target add wasm32-unknown-unknown

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.32.4

    - name: Yarn Install
      run: yarn install

    - name: Yarn Build (builds entire workspace)
      run: yarn build

    - name: Run binaries test script
      run: ./tests/bats/bin/bats tests/binaries.bats || cat ~/Library/Logs/DiagnosticReports/*

    - name: Run integration test script
      run: ./tests/bats/bin/bats tests/integration.bats || cat ~/Library/Logs/DiagnosticReports/*
    